apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-argo-app
  namespace: rabbitmq-test
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-test
  project: default
  source:
    repoURL: https://github.com/ugurserhattoy/kubernetes-deployments.git
    targetRevision: HEAD
    path: rabbitmq

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true